# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eadce60a8ef436f2dd9fe468dbe3cc0cb883ac275d0bc38ba0c56e7757561b13b78208a8ac8db2a4b1d7636656fffb4ccead4f5787c93b5d27a83ab6f29e8f09

test:
  secret_key_base: fdf45958fb8f21787cb5e6d3da6cb5b3e39edb262cd4510e5740b91d054013e52ea6e44aa4eb2bfda27f028f5036f3642939e2e32c7512e6d13203c7059e34b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
